backend:
 name: git-gateway
 branch: main

media_folder: static/images
public_folder: ../../static/images/

collection:
 - name: "name-chars"
   preview: false
   label: "Name Chars"
   folder: "content/name-chars"
   create: true
   slug: "{{slug}}"
   fields: 
    - {label: "Name", name: 'name', widget: "string"}
    - {label: "Brithday Dates", name: 'brithday-dates', wdiget: "string"}
    - {label: "Featured Image", name: 'featured-image', wdiget: "image"}
    - {label: "Body", name: 'body', wdiget: "markdown"}
    